// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2l0YLzA5qZMin3zzARi6ySFv7LoFgaWQ',
    appId: '1:193541270551:web:c809a7632a0089d5ccc052',
    messagingSenderId: '193541270551',
    projectId: 'crowdapp-5cbe2',
    authDomain: 'crowdapp-5cbe2.firebaseapp.com',
    storageBucket: 'crowdapp-5cbe2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNU6AdBXO9a8lYaPE1cUK2KdRy6INbRHA',
    appId: '1:193541270551:android:4b54d4e0229a0098ccc052',
    messagingSenderId: '193541270551',
    projectId: 'crowdapp-5cbe2',
    storageBucket: 'crowdapp-5cbe2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKLro8Yh5Z2ilmuioArIoPu1THhlbM2sQ',
    appId: '1:193541270551:ios:ce7cba61b86f32e4ccc052',
    messagingSenderId: '193541270551',
    projectId: 'crowdapp-5cbe2',
    storageBucket: 'crowdapp-5cbe2.appspot.com',
    iosBundleId: 'com.example.crowdapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKLro8Yh5Z2ilmuioArIoPu1THhlbM2sQ',
    appId: '1:193541270551:ios:ce7cba61b86f32e4ccc052',
    messagingSenderId: '193541270551',
    projectId: 'crowdapp-5cbe2',
    storageBucket: 'crowdapp-5cbe2.appspot.com',
    iosBundleId: 'com.example.crowdapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2l0YLzA5qZMin3zzARi6ySFv7LoFgaWQ',
    appId: '1:193541270551:web:3d97a88f8c3b2d96ccc052',
    messagingSenderId: '193541270551',
    projectId: 'crowdapp-5cbe2',
    authDomain: 'crowdapp-5cbe2.firebaseapp.com',
    storageBucket: 'crowdapp-5cbe2.appspot.com',
  );
}
