// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR0AE7Eg3K-KmrKDRCDJbtUCRnTDVDp1M',
    appId: '1:1002840515813:web:2e0f301e1814fdbb79e00c',
    messagingSenderId: '1002840515813',
    projectId: 'monprojet-848d7',
    authDomain: 'monprojet-848d7.firebaseapp.com',
    storageBucket: 'monprojet-848d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-6QJy8GV2KqOG_9vJXCV1grCO2OupdD8',
    appId: '1:1002840515813:android:198228d7f67a309579e00c',
    messagingSenderId: '1002840515813',
    projectId: 'monprojet-848d7',
    storageBucket: 'monprojet-848d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh40ejwcAjvYUgSTyXZuaYp1uwLXFtQXk',
    appId: '1:1002840515813:ios:8d13b76f8bfe606a79e00c',
    messagingSenderId: '1002840515813',
    projectId: 'monprojet-848d7',
    storageBucket: 'monprojet-848d7.appspot.com',
    iosBundleId: 'com.example.crowdapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh40ejwcAjvYUgSTyXZuaYp1uwLXFtQXk',
    appId: '1:1002840515813:ios:8d13b76f8bfe606a79e00c',
    messagingSenderId: '1002840515813',
    projectId: 'monprojet-848d7',
    storageBucket: 'monprojet-848d7.appspot.com',
    iosBundleId: 'com.example.crowdapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR0AE7Eg3K-KmrKDRCDJbtUCRnTDVDp1M',
    appId: '1:1002840515813:web:5380c53318cf71ba79e00c',
    messagingSenderId: '1002840515813',
    projectId: 'monprojet-848d7',
    authDomain: 'monprojet-848d7.firebaseapp.com',
    storageBucket: 'monprojet-848d7.appspot.com',
  );

}